service: parameter-store-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.13
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:PutParameter
        - ssm:GetParameter
        - ssm:DeleteParameter
        - ssm:GetParametersByPath
      Resource: "*"

  apiGateway:
    apiKeys:
      - ParameterApiKey  # Nombre de la API Key
    usagePlan:
      quota:
        limit: 100      # Límite de peticiones/mes
        offset: 1
        period: MONTH
      throttle:
        burstLimit: 10  # Máximo de peticiones/segundo
        rateLimit: 5 # rate Peticiones/segundo

functions:
  createParam:
    handler: src/createParam.handler
    description: Create a new parameter
    package:
      individually: true
      patterns:
        - "!./**"
        - "src/createParam.py"
    events:
      - http:
          path: parameters
          method: post
          cors: true
          private: true
  
  updateParam:
    handler: src/updateParam.handler
    description: Update an existing parameter
    package:
      individually: true
      patterns:
        - "!./**"
        - "src/updateParam.py"
    events:
      - http:
          path: parameters
          method: patch
          cors: true
          private: true

  getParam:
    handler: src/getParam.handler
    description: Get a parameter from AWS Systems Manager Parameter Store
    package:
      individually: true
      patterns:
        - "!./**"
        - "src/getParam.py"
    events:
      - http:
          path: parameters
          method: get
          cors: true
          private: true 
  
  deleteParam:
    handler: src/deleteParam.handler
    description: Delete a parameter
    package:
      individually: true
      patterns:
        - "!./**"
        - "src/deleteParam.py"
    events:
      - http:
          path: parameters
          method: delete
          cors: true
          private: true
    
  listParams:
    handler: src/listParams.handler
    description: List parameters by path
    package:
      individually: true
      patterns:
        - "!./**"
        - "src/listParams.py"
    events:
      - http:
          path: parameters/list
          method: get
          cors: true
          private: true